# Generated by Django 5.2.10 on 2026-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Ready To Ship', 'Ready To Ship'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('Canceled', 'Canceled')], default='pending', max_length=50),
        ),
    ]
